<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-09T11:13:31 SAST" name="Default suite" finished-at="2021-11-09T11:13:33 SAST" duration-ms="1372">
    <groups>
    </groups>
    <test started-at="2021-11-09T11:13:31 SAST" name="Default test" finished-at="2021-11-09T11:13:33 SAST" duration-ms="1372">
      <class name="runner.ProductRunner">
        <test-method signature="Product_productrates()[pri:2, instance:runner.ProductRunner@44a59da3]" started-at="2021-11-09T11:13:31 SAST" name="Product_productrates" finished-at="2021-11-09T11:13:32 SAST" duration-ms="879" status="FAIL">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Workbook is not found - TestData/rates.xlsx]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Workbook is not found - TestData/rates.xlsx
at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:45)
at Utilities.DataProvider.getDataFromExcelbyQuery(DataProvider.java:34)
at com.exergyRestApi.Repo.Product.ProductsRateRepo.loadTCExpectedResponse(ProductsRateRepo.java:49)
at com.exergyRestApi.Product.Rates.RatesTestCases.Product_60200000(RatesTestCases.java:48)
at runner.ProductRunner.Product_productrates(ProductRunner.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Product_productrates -->
        <test-method is-config="true" signature="EndTests()[pri:0, instance:runner.ProductRunner@44a59da3]" started-at="2021-11-09T11:13:32 SAST" name="EndTests" finished-at="2021-11-09T11:13:33 SAST" duration-ms="444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTests -->
      </class> <!-- runner.ProductRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
