<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tokyos-Air" failures="2" tests="14" name="runner.PartyVerificationRestRunner" time="73.043" errors="1" timestamp="2021-10-26T10:31:47 SAST" skipped="0">
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_001_PersonIdentification_Basic" time="12.978"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_002_PersonIdentification_Basic_Invalid_ID" time="4.538"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_003_PersonIdentification_Enhanced" time="6.633"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_004_PersonIdentification_Enhanced_Invalid_ID" time="2.780"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_005_PersonIdentificationComprehensiveWithMortalityInformation" time="6.018"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_006_PersonIdentificationComprehensiveWithMortalityInformation_Invalid_ID" time="2.572"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_007_PersonVerification_Risk_Rating_Low_IdentityNumber" time="6.019"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_008_PersonVerification_Risk_Rating_Low_IdentityNumber_Invalid_ID" time="4.945">
    <failure message="The following asserts failed:
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at runner.PartyVerificationRestRunner.TC_008_PersonVerification_Risk_Rating_Low_IdentityNumber_Invalid_ID(PartyVerificationRestRunner.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_008_PersonVerification_Risk_Rating_Low_IdentityNumber_Invalid_ID -->
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_009_PersonVerification_Risk_Rating_High_IdentityNumber" time="4.062"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_010_PersonVerificationRiskRatinghigh_Identitynumber_invalid_ID" time="3.844">
    <error message="JSONObject[&quot;ErrorCode&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["ErrorCode"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at com.exergyRestApi.PartyVerification.TC_010.PersonVerification_RiskRating_HighIdentityNumber_Invalid_ID(TC_010.java:48)
at runner.PartyVerificationRestRunner.TC_010_PersonVerificationRiskRatinghigh_Identitynumber_invalid_ID(PartyVerificationRestRunner.java:108)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_010_PersonVerificationRiskRatinghigh_Identitynumber_invalid_ID -->
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_011_PersonVerification_RiskRating_Low_Passport" time="3.877"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_012_PersonVerification_RiskRating_Low_Passport_Invalid_Passport" time="3.321"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_013_PersonVerification_RiskRating_High_Passport" time="5.482"/>
  <system-out/>
  <testcase classname="runner.PartyVerificationRestRunner" name="TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport" time="5.974">
    <failure message="The following asserts failed:
	expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at runner.PartyVerificationRestRunner.TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport(PartyVerificationRestRunner.java:146)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport -->
  <system-out/>
</testsuite> <!-- runner.PartyVerificationRestRunner -->
